log_config_path: "/home/taylor/code/go/src/MySQLNotifier/config/log_config.xml"

mysql:
    address: "127.0.0.1:3306"
    user: "root"
    password: "root"
    dbname: "youmi"

redis:
    address: "127.0.0.1:6379"
    db: 0
    password:
